export const CATEGORIES = [
  "For you",
  "Zeal Headline News",
  "Zeal Global",
  "Zeal Entertainment",
  "Breaking",
  "Viral Videos",
  "Politics",
  "Headlines",
  "Weather",
  "Top US News",
  "UK Top News",
  "EU News",
  "Asian News",
  "Celebrity News",
  "Top Movies",
  "Trending Music",
  "Hot Interviews",
  "Economy",
  "Personal Finance",
  "Market Watch",
  "Startup News",
  "Entrepreneurship",
  "E-Commerce",
  "Latest Tech News",
  "Artificial Intelligence",
  "Crypto",
  "Fintech",
  "Cartech",
  "Gadgets Buying Guide",
  "Health News",
  "Food & Nutrition",
  "Travel & Tourism",
  "Style & Beauty",
  "Family & Parenting",
  "Top Sports News",
  "UK Premiership",
  "Basketball",
  "Gaming",
  "Latest Job News",
  "Career Tips",
  "Top Global Jobs",
];
