import { useQuery } from '@tanstack/react-query';
import { apiClient } from '@/lib/apiClient';
import { AnalyticsResponse } from '@/types/analytics';

export function useAnalyticsData() {
  return useQuery<AnalyticsResponse>({
    queryKey: ['analytics'],
    queryFn: () => apiClient('/api/v1/admin/analytics'),
    staleTime: 5 * 60 * 1000, // 5 minutes
    gcTime: 10 * 60 * 1000, // 10 minutes
    retry: 2,
    refetchOnWindowFocus: false,
  });
}

// Helper function to calculate user vs auto generated posts from source_distribution
export function getPostSourceBreakdown(analytics: AnalyticsResponse | undefined) {
  if (!analytics) {
    return { userGenerated: 0, autoGenerated: 0, total: 0 };
  }

  const userGenerated = analytics.source_distribution.find(s => s.source === 'user')?.count || 0;
  const autoGenerated = analytics.source_distribution.find(s => s.source === 'auto')?.count || 0;
  const total = userGenerated + autoGenerated;

  return {
    userGenerated,
    autoGenerated,
    total
  };
}

// Helper function to get top posts by views
export function getTopPostsByViews(analytics: AnalyticsResponse | undefined, limit: number = 10) {
  if (!analytics) return [];

  return analytics.posts_views
    .sort((a, b) => parseInt(b.views) - parseInt(a.views))
    .slice(0, limit);
}

// Helper function to format chart data for category distribution over time
export function getCategoryChartData(analytics: AnalyticsResponse | undefined) {
  if (!analytics) return [];

  // Transform category_distribution into chart format
  return analytics.category_distribution.map(item => ({
    category: item.category,
    count: item.count,
  }));
}